// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANEWczgMs7b5t7ovdo1g-WzC_KcKUcZrY',
    appId: '1:949702845992:web:0997424148453a4b13371d',
    messagingSenderId: '949702845992',
    projectId: 'flutterfirebaseproject-57205',
    authDomain: 'flutterfirebaseproject-57205.firebaseapp.com',
    storageBucket: 'flutterfirebaseproject-57205.appspot.com',
    measurementId: 'G-PS9GM072QM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqvrfTJUHdaYBWmLwvHDAPa-wDhbRnigc',
    appId: '1:949702845992:android:0f7e5c0b5d099adb13371d',
    messagingSenderId: '949702845992',
    projectId: 'flutterfirebaseproject-57205',
    storageBucket: 'flutterfirebaseproject-57205.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi7U-NergRE4g5cH5SMEyI4JuUcjzgP2A',
    appId: '1:949702845992:ios:4792d992d02ba13613371d',
    messagingSenderId: '949702845992',
    projectId: 'flutterfirebaseproject-57205',
    storageBucket: 'flutterfirebaseproject-57205.appspot.com',
    iosClientId: '949702845992-5ntrjr7cdks1kdilef4v7500moaoiu7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi7U-NergRE4g5cH5SMEyI4JuUcjzgP2A',
    appId: '1:949702845992:ios:4792d992d02ba13613371d',
    messagingSenderId: '949702845992',
    projectId: 'flutterfirebaseproject-57205',
    storageBucket: 'flutterfirebaseproject-57205.appspot.com',
    iosClientId: '949702845992-5ntrjr7cdks1kdilef4v7500moaoiu7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );
}
